name: Farbarena
version: 0.0.1
api: ["1.0.12"]
author: DenoneroDev
website: https://königsmine.de
load: STARTUP
main: deno.Main

commands: 
   farbarena:
      description: Öffnet das Farbarena Gamemenü
      aliases: ["farb", "arena"]